default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        stages: [commit]
        language: system
        entry: pipenv run yapf -ir .
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort .
        types: [python]

      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pipenv run pylint msgraphcore --disable=W --rcfile=.pylintrc
        types: [python]

      - id: pytest-unit
        name: pytest-unit
        stages: [commit]
        language: system
        entry: pipenv run coverage run -m pytest tests/unit
        types: [python]

      - id: pytest-integration
        name: pytest-integration
        stages: [commit]
        language: system
        entry: pipenv run coverage run -m pytest tests/integration
        types: [python]
