name: Publish MsGraph-Core package to TestPyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Create release and publish distribution to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        with:
          python-version: 3.8
      - name: Install dependencies
        run: >-
          python -m pip install --upgrade pip
          python -m pip install flit
      - name: Publish distibution to TestPyPI
        if: github.repository == 'microsoftgraph/msgraph-sdk-python-core' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: >-
          flit publish --repository https://test.pypi.org/legacy/ --username msgraphsdkteam --password ${{ secrets.TEST_PYPI_API_TOKEN }}
