name: Publish MsGraph-Core package to TestPyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Create release and publish distribution to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install flit
        run: |
          pip install flit
      - name: Publish the distibution to TestPyPI
        if: github.repository == 'microsoftgraph/msgraph-sdk-python-core'
        run: flit publish
        env:
          FLIT_INDEX_URL: https://test.pypi.org/legacy/
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
