name: Publish MsGraph-Core package to PyPI

on:
  workflow_dispatch:
  push:
    branches: [ kiota/long-term-branch ]
  pull_request:
    branches: [ kiota/long-term-branch ]

jobs:
  publish:
    name: Create release and publish distribution to PyPI
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/kiota/long-term-branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
