name: Create a release

on:
  push:
    branches: [kiota/long-term-branch]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - name: Build
          uses: ./.github/workflows/python.yml

  publish:
    name: Publish distribution to PyPI
    runs-on: ubuntu-latest
    environment: pypi_prod
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  autorelease:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build, publish]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Release Notes
        run: |
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        if: github.repository == 'microsoftgraph/msgraph-sdk-python-core' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


